### PR TITLE
One create tables for series

### PR DESCRIPTION
**Pull request by SebastianGerS**
Does this look okey?

made some minor changes to the models you (Oleg) created as well to create bindings to the new tables and models
#44

### CODE REVIEW

**Review by Oleg-Lopes — CHANGES_REQUESTED** [review]
add actor/director and etc _in_episode on Person model since you are calling this relationships from Episode model.
Also you have serie_person table which doesn't indicate which person doing what. So, like with episodes and movies - we must have serie_actor, serie_director and etc.

**Comment by SebastianGerS** [comment]
@Oleg-Lopes  sure about that??

 think you some how looking at an earlier version, i do not have a serie_person table in my repository, tried to push again and it already seams up to date...
The relationships in the person table are added but incorrectly references a serie_screenwriter table etc, will fix this.

in regards to the serie_producer_table etc. I'm leaning towards that they are unnececary, all that information will be available thru the epsiode_producer_table etc ( we could just get all the actors from all episodes and display them in other of how many episodes they have apeerd in.
Seams like it would just couse to much duplication of information otherwise which seams unnecessary

**Comment by SebastianGerS** [comment]
@anna.roos made some good sugestions yesterday that we shuld have a title table that links, episodes, movies,series and seasons altogether. Then we we can have a title_director_table etc.
But we can talk more about that tomorow!

**Comment by AnnaRoss** [comment]
Sebastian, my lastname is Ross  (not Roos) - therefore I didn't  a notification.

**Comment by AnnaRoss** [comment]
@Oleg-Lopes @SebastianGerS  Are going to be at Chas Academy today? Would be great if we could make some mutual decisions today :smile:

**Comment by AnnaRoss** [comment]
Moreover, @SebastianGerS why do you want to merge directly into master? Shouldn't we use the flow we decided upon? feature-branch-x --> dev --> stage --> master

**Pull request closed without merging**
